"""Core configuration and settings."""

import os
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
CATALOG_DIR = BASE_DIR / "catalog"
CATALOG_FILE = CATALOG_DIR / "catalog.json"
TEMPLATES_FILE = CATALOG_DIR / "templates.json"
RENDERS_DIR = CATALOG_DIR / "renders"

# Defaults
DEFAULT_SEED = 42
DEFAULT_RESOLUTION = 513
DEFAULT_WORLD_SIZE = [1000.0, 150.0, 1000.0]
DEFAULT_TERRAIN_SCALE = 256.0
DEFAULT_OCTAVES = 6
DEFAULT_PERSISTENCE = 0.5
DEFAULT_LACUNARITY = 2.0
DEFAULT_DOMAIN_WARP_STRENGTH = 35.0
DEFAULT_EROSION_DROPLETS = 50000
DEFAULT_HEIGHT_SCALE = 100.0

DEFAULT_MIN_ZONE_DISTANCE = 120.0
DEFAULT_FACTIONS = ["A", "B", "C"]
DEFAULT_MAX_DESTRUCTION = 4
